- pom.xml
- src/main/java/org/folio/edge/oaipmh/MainVerticle.java
- src/main/resources/ephemeral.properties
- src/test/java/org/folio/edge/oaipmh/MainVerticleTest.java
To enable response compression
- edge-common version switched from 0.3.4-SNAPSHOT to 0.3.7-SNAPSHOT;
- EdgeVerticle switched to EdgeVerticle2;
- unit tests added for compression verification.
> EDGOAIPMH-8 - "OAI-PMH: Response compression"

- NEWS.md
- README.md
- ramls/edge-oai-pmh.raml
- ramls/traits/apiKeyParam.raml
- ramls/traits/params.raml
- src/main/java/org/folio/edge/oaipmh/MainVerticle.java
- src/main/java/org/folio/edge/oaipmh/OaiPmhHandler.java
- src/main/java/org/folio/edge/oaipmh/Verb.java
- src/main/java/org/folio/edge/oaipmh/utils/OaiPmhOkapiClient.java
- src/test/java/org/folio/edge/oaipmh/MainVerticleTest.java
- src/test/resources/log4j.properties
This is supported by edge-common, but we need to make a few adjustments here to make this work.
Added:
- `GET /oai/<apiKey>?verb=...`
- `POST /oai/<apiKey>?verb=...`
> Add ability to specify API Key as part of the path

- NEWS.md
- pom.xml
The main focus of this release (edge-oai-pmh-2.0.0) was to upgrade login interface and edge-common dependency to actual versions.
> EDGOAIPMH-28 - Release 2.0.0

- Dockerfile
- descriptors/ModuleDescriptor-template.json
Use new Alpine base docker image with more recent Java 8 (222) with +UseContainerSupport, and JAVA_OPTIONS MaxRAMPercentage to manage container memory.
See notes at [FOLIO-2358](https://issues.folio.org/browse/FOLIO-2358).
> EDGOAIPMH-34 FOLIO-2358 manage container memory

- NEWS.md
- descriptors/ModuleDescriptor-template.json
- pom.xml
Release edge-oai-pmh-2.1.0
Updating news, required interface version
> EDGOAIPMH-35 - Release 2.1.0

- NEWS.md
- descriptors/ModuleDescriptor-template.json
- pom.xml
Release v2.1.1 for inclusion in Edelweiss (Q4/2019)
See [EDGOAIPMH-37](https://issues.folio.org/browse/EDGOAIPMH-37)
NOTE: I have not yet run the mvn command to bump the versions and create the tag
> Release 2.1.1

- src/main/java/org/folio/edge/oaipmh/utils/OaiPmhOkapiClient.java
- src/test/java/org/folio/edge/oaipmh/MainVerticleTest.java
- src/test/java/org/folio/edge/oaipmh/utils/OaiPmhMockOkapi.java
Provide a fix for the problem described MODOAIPMH-86 that's compatible with the Daisy release of FOLIO.
This can be achieved by simply not passing the "Accept" header when proxying requests to mod-oai-pmh.  If no Accept header is provided, or `*/*` is specified, mod-oai-pmh will service the request and return text/xml as expected per the OAI-PMH spec.
See [EDGOAIPMH-39](https://issues.folio.org/browse/EDGOAIPMH-39)
> EDGOAIPMH-39 Don't pass Accept header to backend

- pom.xml
- ramls/traits/resps.raml
- src/main/java/org/folio/edge/oaipmh/OaiPmhHandler.java
- src/main/java/org/folio/edge/oaipmh/utils/Constants.java
- src/test/java/org/folio/edge/oaipmh/MainVerticleTest.java
If Accept header is empty or has text/xml value edge-oai-pmh module making requests to mod-oai-pmh otherwise, a 406 Http code is sent.
> EDGOAIPMH-38 Use "Accept: text/xml" or empty Accept when making requests to mod-oai-pmh

- src/main/java/org/folio/edge/oaipmh/OaiPmhHandler.java
- src/test/java/org/folio/edge/oaipmh/OaiPmhTest.java
In order for not to use okapi token and tenant from headers, I override method (I leave the logic of getting the token and tenant ) and use this method for giving ConfigurationsClient. For make request to oai-pmh I use version of this method from parent class.
[https://issues.folio.org/browse/MODOAIPMH-106](url)
> MODOAIPMH-106 Get okapi token and tenant not from headers

- src/main/java/org/folio/edge/oaipmh/service/impl/ModConfigurationService.java
- src/test/java/org/folio/edge/oaipmh/OaiPmhHandlerTest.java
For fix sonar code smells in tests I use assertTrue(true) and replace "+" to "," in Logger error message in service class.
> MODOAIPMH-103 Fix sonar code smells

- NEWS.md
- pom.xml
Release edge-oai-pmh-2.2.1: https://issues.folio.org/browse/EDGOAIPMH-49
This release includes minor bug fixes for edge-oai-pmh module (Q2/2020).
> Tmp release 2.2.1

- src/main/java/org/folio/edge/oaipmh/MainVerticle.java
- src/main/java/org/folio/edge/oaipmh/OaiPmhHandler.java
- src/main/java/org/folio/edge/oaipmh/clients/OaiPmhOkapiClient.java
- src/main/java/org/folio/edge/oaipmh/clients/OaiPmhOkapiClientFactory.java
- src/test/java/org/folio/edge/oaipmh/utils/OaiPmhOkapiClientFactoryTest.java
- src/test/java/org/folio/edge/oaipmh/utils/OaiPmhOkapiClientTest.java
Jira: https://issues.folio.org/browse/EDGOAIPMH-61
Fix memory leak caused by unclosed HTTP clients.
Memory usage graph **before** HTTP client closing.
Memory usage graph **after** HTTP client closing.
Close HTTP client
> EDGOAIPMH-61: 503 status returned after several initial harvests

- src/main/java/org/folio/edge/oaipmh/OaiPmhHandler.java
[EDGOAIPMH-60](https://issues.folio.org/browse/EDGOAIPMH-60) - Check if the response contains records
During the harvesting mod-oai-pmh sends instance uuid to srs to retrieve the underlying record. If the instance does not have underlying SRS record, nothing is included in the output. In some cases when max record per response is small, it might happen that the response will contain resumption token only and no records.
Requirements/Scope:
* Check if the response from mod-oai-pmh contains records and not only resumptionToken
* If there are no records, the module will re-send request to mod-oai-pmh using provided resumptionToken.
* Updated logic
* Implemented unit test
- Does this PR meet or exceed …
> EDGOAIPMH-60 - Check if the response contains records

- pom.xml
SNAPSHOT version in the POM needs to be higher than the last released version (v2.4.1) on master/main.   Setting to 2.4.2-SNAPSHOT.
> set pom to next dev iteration

- NEWS.md
- pom.xml
[EDGOAIPMH-75](https://issues.folio.org/browse/EDGOAIPMH-75) - Kiwi R3 2021 Log4j module release
> EDGOAIPMH-75 - Release 2.4.2

- NEWS.md
- pom.xml
[EDGOAIPMH-77](https://issues.folio.org/browse/EDGOAIPMH-77) - Juniper R2 2021 Log4j module release
> EDGOAIPMH-77 - Release 2.3.3

- pom.xml
Upgrading snapshot version to prevent build failure
> FOLIO-3370 - refenv builds fail, some modules have incorrect snapshot version

- src/main/java/org/folio/edge/oaipmh/OaiPmhHandler.java
- src/test/java/org/folio/edge/oaipmh/OaiPmhTest.java
- src/test/java/org/folio/edge/oaipmh/utils/OaiPmhMockOkapi.java
Jira: https://issues.folio.org/browse/EDGOAIPMH-82
Proxy the response received from okapi 
**Enhancement**
Append the okapi response body to the edge response, therefore a user will be able to see not only Forbidden message but the message with missing permission like "Error in the response from repository: status code - 403, response status message - Forbidden Access requires permission: oai-pmh.records.collection.get"
> EDGEOAIPMH-82: forward the response status code received from okapi instead of 500

- NEWS.md
- pom.xml
https://issues.folio.org/browse/EDGOAIPMH-88 Release edge-oai-pmh 2.5.1 for MG Bugfix
https://issues.folio.org/browse/EDGOAIPMH-87 edge-common 4.4.1 fixing disabled SSL in Vert.x WebClient
> EDGOAIPMH-88: Release edge-oai-pmh 2.5.1 for MG Bugfix

- NEWS.md
- pom.xml
[EDGOAIPMH-93](https://issues.folio.org/browse/EDGOAIPMH-93) - edge-oai-pmh: module release
> Release 2.6.0

- .github/workflows/api-doc.yml
- .github/workflows/api-lint.yml
- .github/workflows/api-schema-lint.yml
- Jenkinsfile
- README.md
- ramls/edge-oai-pmh.raml
[FOLIO-3678](https://issues.folio.org/browse/FOLIO-3678)
Use GitHub Workflows for [api-lint](https://dev.folio.org/guides/api-lint/) and [api-schema-lint](https://dev.folio.org/guides/describe-schema/) and [api-doc](https://dev.folio.org/guides/api-doc/)
(instead of Jenkins-operated CI stages).
> FOLIO-3678 EDGOAIPMH-98 Use GitHub Workflows api-lint and api-schema-lint and api-doc

- pom.xml
Upgrade RMB from the Orchid version 35.0.6 to the Poppy version 35.1.1.
Upgrade Vert.x from 4.3.8 to 4.4.6. Versions 4.3.x have been out of support since March 2023.
Upgrade log4j from 2.17.2 to 2.20.0. edge-common comes with 2.20.0 and we should not downgrade the version.
The Vert.x upgrade indirectly upgrades Netty from 4.1.87.Final to 4.1.100.Final fixing Denial of Service (DoS):
https://nvd.nist.gov/vuln/detail/CVE-2023-44487
https://nvd.nist.gov/vuln/detail/CVE-2023-34462
The RMB upgrade indirectly upgrades Jackson from 2.14.0 to 2.15.0 fixing Number Parse DoS:
https://github.com/FasterXML/jackson-core/pull/827 (PRISMA-2023-0067)
> EDGOAIPMH-108: RMB 35.1.1, Vert.x 4.4.6 fixing Netty/Jackson DoS
