- NEWS.md
- descriptors/DeploymentDescriptor-template.json
- descriptors/ModuleDescriptor-template.json
Module/Deployment Descriptors added
Viachaslau Khandramai <Viachaslau_Khandramai@epam.com>
> JIRA: EDGOAIPMH-5 - Define Module/Deployment Descriptors

- pom.xml
- src/main/java/org/folio/edge/oaipmh/MainVerticle.java
- src/main/java/org/folio/edge/oaipmh/OaiPmhHandler.java
- src/main/java/org/folio/edge/oaipmh/utils/OaiPmhOkapiClient.java
- src/main/java/org/folio/edge/oaipmh/utils/OaiPmhOkapiClientFactory.java
MainVerticle, OaiPmhHandler, OaiPmhOkapiClientFactory, OaiPmhOkapiClient skeletons
Viachaslau Khandramai <Viachaslau_Khandramai@epam.com>
> JIRA: EDGOAIPMH-6 - Define routes in the edge-oai-pmh verticle

- pom.xml
- ramls/schemas/bindings.xjb
- src/main/java/org/folio/edge/oaipmh/Constants.java
- src/main/java/org/folio/edge/oaipmh/OaiPmhHandler.java
- src/main/java/org/folio/edge/oaipmh/ResponseHelper.java
- src/main/java/org/folio/edge/oaipmh/Verb.java
- src/test/java/org/folio/edge/oaipmh/MainVerticleTest.java
OAI-PMH request parameters validation logic
> EDGOAIPMH-13 Validate Query Arguments

- src/main/java/org/folio/edge/oaipmh/Verb.java
> EDGOAIPMH-12 OAI-PMH: Implement Basic Edge Handler

- src/main/resources/aws_ss.properties
- src/main/resources/vault.properties
Add the placeholder secure store properties files for aws param store and vault.
> Adding placeholder secure store properties files

- pom.xml
- ramls/schemas/bindings.xjb
- src/main/java/org/folio/edge/oaipmh/OaiPmhHandler.java
- src/test/java/org/folio/edge/oaipmh/MainVerticleTest.java
- src/test/java/org/folio/edge/oaipmh/utils/OaiPmhMockOkapi.java
- src/test/resources/log4j.properties
- enable support of already compressed response body returned by repository business logic
- updating validation logic to return request parameters in OAI-PMH response
- overriding accessDenied and requestTimeout error messages
- enabling debug for unit tests
> MODOAIPMH-53 OAI-PMH: Response Compression (backend module)

- src/main/resources/ephemeral.properties
- src/test/java/org/folio/edge/oaipmh/MainVerticleTest.java
Small changes related to changing of apikey for consistentency with Postman API Testing project.
> EDGOAIPMH-9 - "OAI-PMH: API Test Setup/Cleanup" (apikey changing)

- Jenkinsfile
> FOLIO-1747 publish docker snapshot

- pom.xml
- src/main/resources/ephemeral.properties
- src/test/java/org/folio/edge/oaipmh/MainVerticleTest.java
- src/test/java/org/folio/edge/oaipmh/utils/OaiPmhOkapiClientTest.java
- edge-common changed to version 2.0.0
- unit tests updated and refactored
> EDGOAIPMH-28 - Upgrade to edge-common v2.0.0

- NEWS.md
- descriptors/ModuleDescriptor-template.json
- pom.xml
https://issues.folio.org/browse/EDGOAIPMH-30 - Release 2.0.1 to update to latest login version
> EDGEOAIPMH-30- Release 2.0.1

- src/main/java/org/folio/edge/oaipmh/OaiPmhHandler.java
- src/main/java/org/folio/edge/oaipmh/utils/Constants.java
- src/main/java/org/folio/edge/oaipmh/utils/OaiPmhOkapiClient.java
- src/test/java/org/folio/edge/oaipmh/utils/OaiPmhMockOkapi.java
Additions for [PR30](https://github.com/folio-org/edge-oai-pmh/pull/30) for solving issue raised in [EDGOAIPMH-39](https://issues.folio.org/browse/EDGOAIPMH-39).
> EDGOAIPMH-39 - Don't pass the Accept header when proxying requests to mod-oai-pmh

- NEWS.md
- pom.xml
Release v2.1.2 containing [EDGOAIPMH-39]( https://issues.folio.org/browse/EDGOAIPMH-39)
See [EDGOAIPMH-40](https://issues.folio.org/browse/EDGOAIPMH-40)
> Release 2.1.2

- descriptors/ModuleDescriptor-template.json
Change versions oai-pmh and mod-login interfaces in ModuleDescriptor file.
[https://issues.folio.org/browse/MODOAIPMH-158](url)
> MODOAIPMH-158 Preparation to EDGOAIPMH release

- NEWS.md
- pom.xml
###Purpose
Release the module.
> Tmp release 2.2.0

- src/main/resources/ephemeral.properties
For integration tests we need new tenant, user and password insert into ephemeral.properties file
[https://issues.folio.org/browse/MODOAIPMH-142](url)
> MODOAIPMH-142 Add new tenant, user and password to properties file

- Dockerfile
- Jenkinsfile
- pom.xml
- src/test/java/org/folio/edge/oaipmh/OaiPmhTest.java
> EDGOAIPMH-50: POC: Update to java 11

- NEWS.md
- pom.xml
> Release 2.3.0

- NEWS.md
- descriptors/ModuleDescriptor-template.json
- pom.xml
- src/main/java/org/folio/edge/oaipmh/MainVerticle.java
###PURPOSE 
Find out which changes weren't move to master and merge them to master as well.
Jira: https://issues.folio.org/browse/EDGOAIPMH-58
> EDGOAIPMH-58: Move not applied changes to master from b2.2 release branch.

- NEWS.md
- pom.xml
[EDGEOAIPMH-65](https://issues.folio.org/browse/EDGOAIPMH-65) - EDGOAIPMH (edge-oai-pmh) release
> EDGEOAIPMH-65 - RELEASE 2.4.0

- pom.xml
[EDGOAIPMH-69](https://issues.folio.org/browse/EDGOAIPMH-69) - Kiwi R3 2021 - Log4j vulnerability verification and correction
> EDGOAIPMH-69 - Kiwi R3 2021 - Log4j vulnerability verification and correction

- NEWS.md
- pom.xml
[EDGOAIPMH-73](https://issues.folio.org/browse/EDGOAIPMH-73) - EDGOAIPMH (edge-oai-pmh) Kiwi Bugfix release
> EDGOAIPMH-73 - Release 2.4.1

- NEWS.md
- pom.xml
[EDGOAIPMH-72](https://issues.folio.org/browse/EDGOAIPMH-72) - EDGOAIPMH (edge-oai-pmh) Juniper Hotfix release
> EDGOAIPMH-72 - Release 2.3.2

- pom.xml
[EDGOAIPMH-74](https://issues.folio.org/browse/EDGOAIPMH-74) - Kiwi R3 2021 - Log4j edge- modules 2.17.0 upgrade
> EDGOAIPMH-74 - Kiwi R3 2021 - Log4j edge- modules 2.17.0 upgrade

- NEWS.md
- pom.xml
[EDGOAIPMH-80](https://issues.folio.org/browse/EDGOAIPMH-80) - Release 2.5.0
> EDGOAIPMH-80 - Release 2.5.0

- PULL_REQUEST_TEMPLATE.md
- src/main/resources/log4j2-json.properties
- src/main/resources/log4j2.properties
[EDGOAIPMH-91](https://issues.folio.org/browse/EDGOAIPMH-91) - Logging improvement - Configuration
Logging should be improved for more productive troubleshooting.
Added required settings
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is paramount if that is …
> EDGOAIPMH-91 - Logging improvement - Configuration

- pom.xml
- ramls/edge-oai-pmh.raml
- ramls/schemas/consortium.json
- ramls/schemas/consortiumCollection.json
- ramls/schemas/tenant.json
- ramls/schemas/tenantCollection.json
- ramls/schemas/userTenant.json
- ramls/schemas/userTenantCollection.json
- ramls/schemas/uuid.schema
- src/main/java/org/folio/edge/oaipmh/clients/ConsortiaClient.java
- src/main/java/org/folio/edge/oaipmh/clients/ConsortiaTenantClient.java
- src/main/java/org/folio/edge/oaipmh/clients/OaiPmhOkapiClientFactory.java
- src/test/java/org/folio/edge/oaipmh/utils/ConsortiaTenantClientTest.java
- src/test/java/org/folio/edge/oaipmh/utils/OaiPmhMockOkapi.java
- src/test/java/org/folio/edge/oaipmh/utils/OaiPmhOkapiClientFactoryTest.java
- src/test/resources/mocks/consortiaTenants.json
- src/test/resources/mocks/consortiumCollection.json
- src/test/resources/mocks/emptyConsortiumCollection.json
- src/test/resources/mocks/emptyUserTenantsCollection.json
- src/test/resources/mocks/userTenantsCollection.json
- src/test/resources/mocks/userTenantsCollectionForEmptyConsortia.json
[EDGOAIPMH-100](https://issues.folio.org/browse/EDGOAIPMH-100) - ConsortiaTenant API Client
Client should accept tenantId and return list of tenants from consortia. In case tenant isn't consortial client should return initial tenantId as element of list.
* Implemented ConsortiaTenant client
* Added unit tests
Ideally all of the PRs involved in breaking …
> EDGOAIPMH-100 - ConsortiaTenant API Client

- src/main/java/org/folio/edge/oaipmh/OaiPmhHandler.java
- src/main/java/org/folio/edge/oaipmh/clients/ConsortiaClient.java
- src/main/java/org/folio/edge/oaipmh/clients/ConsortiaTenantClient.java
- src/main/java/org/folio/edge/oaipmh/utils/Constants.java
- src/main/resources/ephemeral.properties
- src/test/java/org/folio/edge/oaipmh/OaiPmhTest.java
- src/test/java/org/folio/edge/oaipmh/utils/ConsortiaTenantClientTest.java
- src/test/java/org/folio/edge/oaipmh/utils/OaiPmhMockOkapi.java
- src/test/resources/mocks/ListRecordsConsortiaResponse.xml
- src/test/resources/mocks/ListRecordsConsortiaResponse2.xml
- src/test/resources/mocks/ListRecordsConsortiaResponse3.xml
- src/test/resources/mocks/ListRecordsWithTokenResponse.xml
- src/test/resources/mocks/userTenantsCollection.json
[EDGOAIPMH-99](https://issues.folio.org/browse/EDGOAIPMH-99) - Harvesting Across Tenants Orchestrator
Component should orchestrate harvestings across several tenants starting them one by one.
* Implemented orchestrator logic
* Added unit tests
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the …
> EDGOAIPMH-99 - Harvesting Across Tenants Orchestrator

- README.md
- src/main/java/org/folio/edge/oaipmh/OaiPmhHandler.java
[EDGOAIPMH-99](https://issues.folio.org/browse/EDGOAIPMH-99) - Harvesting Across Tenants Orchestrator 
Component should orchestrate harvestings across several tenants starting them one by one.
Fixed logic to avoid adding `user-tenants.collection.get` for non-consortia environments
Ideally all of the PRs involved in breaking changes would be merged in the …
> EDGOAIPMH-99 - Harvesting Across Tenants Orchestrator 

- pom.xml
- src/main/java/org/folio/edge/oaipmh/OaiPmhHandler.java
- src/test/java/org/folio/edge/oaipmh/OaiPmhTest.java
- src/test/java/org/folio/edge/oaipmh/utils/ConsortiaTenantClientTest.java
[EDGOAIPMH-107](https://issues.folio.org/browse/EDGOAIPMH-107) - Update edge-common version
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is paramount if that is to be achieved, especially as the number of intermodule and inter-team dependencies increase. …
> EDGOAIPMH-107 - Update edge-common version

- NEWS.md
- pom.xml
- src/main/java/org/folio/edge/oaipmh/OaiPmhHandler.java
- src/test/java/org/folio/edge/oaipmh/OaiPmhTest.java
- src/test/java/org/folio/edge/oaipmh/utils/ConsortiaTenantClientTest.java
[EDGOAIPMH-109](https://issues.folio.org/browse/EDGOAIPMH-109) - edge-oai-pmh: module release
> Release 2.7.1

- src/main/java/org/folio/edge/oaipmh/clients/ConsortiaClient.java
[EDGOAIPMH-110](https://issues.folio.org/browse/EDGOAIPMH-110) - Retrieving tenants limit issue
Fix issue with retrieving tenants limit.
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is paramount if that is to be achieved, especially as the number of …
> EDGOAIPMH-110 - Retrieving tenants limit issue

- pom.xml
[EDGOAIPMH-114](https://folio-org.atlassian.net/browse/EDGOAIPMH-114) - edge-oai-pmh: Upgrade RAML Module Builder
Update RMB
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is paramount if that is to be achieved, especially as the number of intermodule and …
> EDGOAIPMH-114 - edge-oai-pmh: Upgrade RAML Module Builder

- pom.xml
[EDGOAIPMH-114](https://folio-org.atlassian.net/browse/EDGOAIPMH-114) - edge-oai-pmh: Upgrade edge-common
Upgrade edge-common to 4.6.0
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is paramount if that is to be achieved, especially as the number of …
> EDGOAIPMH-114 - edge-oai-pmh: Upgrade edge-common

- NEWS.md
- pom.xml
[EDGOAIPMH-115](https://folio-org.atlassian.net/browse/EDGOAIPMH-115) - edge-oai-pmh: module release
Release 2.9.0
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is paramount if that is to be achieved, especially as the number of intermodule and inter-team …
> EDGOAIPMH-115 - Release 2.9.0

- Dockerfile
- Jenkinsfile
- pom.xml
[EDGOAIPMH-128](https://folio-org.atlassian.net/browse/EDGOAIPMH-128) - Update to edge-oai-pmh Java 21
Upgrading Java version to Java 21.
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is paramount if that is to be achieved, especially as the number of …
> EDGOAIPMH-128 - Update to edge-oai-pmh Java 21

- pom.xml
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is paramount if that is to be achieved, especially as the number of intermodule and inter-team dependencies increase.
While it's helpful for reviewers to help identify potential problems, ensuring that it's …
> EDGOAIPMH-128 - revert log4j major upgrade

- pom.xml
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is paramount if that is to be achieved, especially as the number of intermodule and inter-team dependencies increase.
While it's helpful for reviewers to help identify potential problems, ensuring that it's …
>  EDGOAIPMH-128 bump up edge-common

- NEWS.md
- pom.xml
[EDGOAIPMH-130](https://folio-org.atlassian.net/browse/EDGOAIPMH-130) - Release 2.11.0
> EDGOAIPMH-130 - Release 2.11.0
